ALTER TABLE "users" ADD COLUMN "source" varchar(20) DEFAULT 'github' NOT NULL;
ALTER TABLE "packages" ADD COLUMN "source" varchar(20) DEFAULT 'github' NOT NULL;
ALTER TABLE "sync_metadata" ADD COLUMN "source" varchar(20) DEFAULT 'github' NOT NULL;
ALTER TABLE "users" RENAME COLUMN "github_id" TO "source_id";
ALTER TABLE "packages" RENAME COLUMN "github_id" TO "source_id";
ALTER TABLE "users" DROP CONSTRAINT "users_github_id_unique";
ALTER TABLE "users" DROP CONSTRAINT "users_username_unique";
ALTER TABLE "packages" DROP CONSTRAINT "packages_github_id_unique";
ALTER TABLE "sync_metadata" DROP CONSTRAINT "sync_metadata_topic_unique";
ALTER TABLE "users" ADD CONSTRAINT "users_source_source_id_unique" UNIQUE("source","source_id");
ALTER TABLE "users" ADD CONSTRAINT "users_source_username_unique" UNIQUE("source","username");
ALTER TABLE "packages" ADD CONSTRAINT "packages_source_source_id_unique" UNIQUE("source","source_id");
ALTER TABLE "sync_metadata" ADD CONSTRAINT "sync_metadata_source_topic_unique" UNIQUE("source","topic");
