// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Package struct {
	ID             int32
	GithubID       int32
	Name           string
	FullName       string
	Owner          string
	OwnerAvatarUrl pgtype.Text
	Description    pgtype.Text
	Version        pgtype.Text
	Stars          int32
	Forks          int32
	OpenIssues     int32
	License        pgtype.Text
	Homepage       pgtype.Text
	RepositoryUrl  string
	Topics         pgtype.Text
	PackageType    string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	PushedAt       pgtype.Timestamptz
	CachedAt       pgtype.Timestamptz
}

type SyncMetadatum struct {
	ID         int32
	Topic      string
	LastSyncAt pgtype.Timestamptz
	TotalCount pgtype.Int4
	NextSyncAt pgtype.Timestamptz
}
