// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Package struct {
	ID              int32
	Source          string
	SourceID        int64
	Name            string
	FullName        string
	OwnerID         string
	Description     pgtype.Text
	Version         pgtype.Text
	Stars           int32
	Forks           int32
	OpenIssues      int32
	License         pgtype.Text
	Homepage        pgtype.Text
	RepositoryUrl   string
	Topics          []byte
	PackageType     string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	PushedAt        pgtype.Timestamptz
	CachedAt        pgtype.Timestamptz
	Status          string
	Origin          string
	SubmittedBy     pgtype.Text
	SubmittedAt     pgtype.Timestamptz
	ReviewedBy      pgtype.Text
	ReviewedAt      pgtype.Timestamptz
	RejectionReason pgtype.Text
	PrimaryLanguage pgtype.Text
	HasZigFiles     pgtype.Bool
	HasBuildZigZon  pgtype.Bool
}

type PackageContent struct {
	ID         int32
	PackageID  int32
	Readme     pgtype.Text
	Tags       []byte
	Files      []byte
	ZonContent pgtype.Text
	LastSync   pgtype.Timestamptz
}

type SyncMetadatum struct {
	ID         int32
	Source     string
	Topic      string
	LastSyncAt pgtype.Timestamptz
	TotalCount pgtype.Int4
	NextSyncAt pgtype.Timestamptz
	SyncCursor pgtype.Text
}

type User struct {
	ID        string
	Source    string
	SourceID  int64
	Username  string
	AvatarUrl pgtype.Text
	Bio       pgtype.Text
	HtmlUrl   pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
