// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSyncMetadata = `-- name: GetSyncMetadata :one
SELECT id, topic, last_sync_at, total_count, next_sync_at
FROM sync_metadata
WHERE topic = $1
`

func (q *Queries) GetSyncMetadata(ctx context.Context, topic string) (SyncMetadatum, error) {
	row := q.db.QueryRow(ctx, getSyncMetadata, topic)
	var i SyncMetadatum
	err := row.Scan(
		&i.ID,
		&i.Topic,
		&i.LastSyncAt,
		&i.TotalCount,
		&i.NextSyncAt,
	)
	return i, err
}

const upsertPackage = `-- name: UpsertPackage :exec
INSERT INTO packages (
  github_id, name, full_name, owner, owner_avatar_url,
  description, version, stars, forks, open_issues,
  license, homepage, repository_url, topics,
  package_type, created_at, updated_at, pushed_at, cached_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
  $11, $12, $13, $14, $15, $16, $17, $18, now()
)
ON CONFLICT (github_id) DO UPDATE SET
  name           = EXCLUDED.name,
  full_name      = EXCLUDED.full_name,
  description    = EXCLUDED.description,
  version        = EXCLUDED.version,
  stars          = EXCLUDED.stars,
  forks          = EXCLUDED.forks,
  open_issues    = EXCLUDED.open_issues,
  license        = EXCLUDED.license,
  homepage       = EXCLUDED.homepage,
  topics         = EXCLUDED.topics,
  updated_at     = EXCLUDED.updated_at,
  pushed_at      = EXCLUDED.pushed_at,
  cached_at      = now()
`

type UpsertPackageParams struct {
	GithubID       int32
	Name           string
	FullName       string
	Owner          string
	OwnerAvatarUrl pgtype.Text
	Description    pgtype.Text
	Version        pgtype.Text
	Stars          int32
	Forks          int32
	OpenIssues     int32
	License        pgtype.Text
	Homepage       pgtype.Text
	RepositoryUrl  string
	Topics         pgtype.Text
	PackageType    string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	PushedAt       pgtype.Timestamptz
}

func (q *Queries) UpsertPackage(ctx context.Context, arg UpsertPackageParams) error {
	_, err := q.db.Exec(ctx, upsertPackage,
		arg.GithubID,
		arg.Name,
		arg.FullName,
		arg.Owner,
		arg.OwnerAvatarUrl,
		arg.Description,
		arg.Version,
		arg.Stars,
		arg.Forks,
		arg.OpenIssues,
		arg.License,
		arg.Homepage,
		arg.RepositoryUrl,
		arg.Topics,
		arg.PackageType,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.PushedAt,
	)
	return err
}

const upsertSyncMetadata = `-- name: UpsertSyncMetadata :exec
INSERT INTO sync_metadata (topic, last_sync_at, total_count, next_sync_at)
VALUES ($1, now(), $2, now() + interval '1 hour')
ON CONFLICT (topic) DO UPDATE SET
  last_sync_at = now(),
  total_count  = EXCLUDED.total_count,
  next_sync_at = now() + interval '1 hour'
`

type UpsertSyncMetadataParams struct {
	Topic      string
	TotalCount pgtype.Int4
}

func (q *Queries) UpsertSyncMetadata(ctx context.Context, arg UpsertSyncMetadataParams) error {
	_, err := q.db.Exec(ctx, upsertSyncMetadata, arg.Topic, arg.TotalCount)
	return err
}
