// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSyncMetadata = `-- name: GetSyncMetadata :one
SELECT id, source, topic, last_sync_at, total_count, next_sync_at, sync_cursor
FROM sync_metadata
WHERE source = $1 AND topic = $2
`

type GetSyncMetadataParams struct {
	Source string
	Topic  string
}

func (q *Queries) GetSyncMetadata(ctx context.Context, arg GetSyncMetadataParams) (SyncMetadatum, error) {
	row := q.db.QueryRow(ctx, getSyncMetadata, arg.Source, arg.Topic)
	var i SyncMetadatum
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.Topic,
		&i.LastSyncAt,
		&i.TotalCount,
		&i.NextSyncAt,
		&i.SyncCursor,
	)
	return i, err
}

const saveSyncCursor = `-- name: SaveSyncCursor :exec
INSERT INTO sync_metadata (source, topic, last_sync_at, total_count, next_sync_at, sync_cursor)
VALUES ($1, $2, 'epoch', $3, now() + interval '1 hour', $4)
ON CONFLICT (source, topic) DO UPDATE SET
  total_count = EXCLUDED.total_count,
  sync_cursor = EXCLUDED.sync_cursor
`

type SaveSyncCursorParams struct {
	Source     string
	Topic      string
	TotalCount pgtype.Int4
	SyncCursor pgtype.Text
}

// Checkpoints an in-progress pass: persists the pagination cursor and the
// running total without bumping the cooldown, so an interrupted run resumes.
// last_sync_at is only ever advanced by UpsertSyncMetadata on completion; the
// INSERT branch (a (source, topic)'s first-ever checkpoint) seeds it with
// 'epoch' so a resumed *first* sync is not mistaken for an incremental pass and
// truncated by the freshness cutoff. The UPDATE branch deliberately leaves
// last_sync_at alone, preserving the previous completed pass as the watermark.
func (q *Queries) SaveSyncCursor(ctx context.Context, arg SaveSyncCursorParams) error {
	_, err := q.db.Exec(ctx, saveSyncCursor,
		arg.Source,
		arg.Topic,
		arg.TotalCount,
		arg.SyncCursor,
	)
	return err
}

const upsertPackage = `-- name: UpsertPackage :exec
INSERT INTO packages (
  source, source_id, name, full_name, owner_id,
  description, version, stars, forks, open_issues,
  license, homepage, repository_url, topics,
  package_type, created_at, updated_at, pushed_at,
  status, origin, cached_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9,
  $10, $11, $12, $13, $14, $15, $16, $17, $18,
  $19, $20, now()
)
ON CONFLICT (source, source_id) DO UPDATE SET
  name           = EXCLUDED.name,
  full_name      = EXCLUDED.full_name,
  owner_id       = EXCLUDED.owner_id,
  description    = EXCLUDED.description,
  version        = EXCLUDED.version,
  stars          = EXCLUDED.stars,
  forks          = EXCLUDED.forks,
  open_issues    = EXCLUDED.open_issues,
  license        = EXCLUDED.license,
  homepage       = EXCLUDED.homepage,
  topics         = EXCLUDED.topics,
  updated_at     = EXCLUDED.updated_at,
  pushed_at      = EXCLUDED.pushed_at,
  cached_at      = now()
`

type UpsertPackageParams struct {
	Source        string
	SourceID      int64
	Name          string
	FullName      string
	OwnerID       string
	Description   pgtype.Text
	Version       pgtype.Text
	Stars         int32
	Forks         int32
	OpenIssues    int32
	License       pgtype.Text
	Homepage      pgtype.Text
	RepositoryUrl string
	Topics        []byte
	PackageType   string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	PushedAt      pgtype.Timestamptz
	Status        string
	Origin        string
}

func (q *Queries) UpsertPackage(ctx context.Context, arg UpsertPackageParams) error {
	_, err := q.db.Exec(ctx, upsertPackage,
		arg.Source,
		arg.SourceID,
		arg.Name,
		arg.FullName,
		arg.OwnerID,
		arg.Description,
		arg.Version,
		arg.Stars,
		arg.Forks,
		arg.OpenIssues,
		arg.License,
		arg.Homepage,
		arg.RepositoryUrl,
		arg.Topics,
		arg.PackageType,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.PushedAt,
		arg.Status,
		arg.Origin,
	)
	return err
}

const upsertSyncMetadata = `-- name: UpsertSyncMetadata :exec
INSERT INTO sync_metadata (source, topic, last_sync_at, total_count, next_sync_at, sync_cursor)
VALUES ($1, $2, now(), $3, now() + interval '1 hour', NULL)
ON CONFLICT (source, topic) DO UPDATE SET
  last_sync_at = now(),
  total_count  = EXCLUDED.total_count,
  next_sync_at = now() + interval '1 hour',
  sync_cursor  = NULL
`

type UpsertSyncMetadataParams struct {
	Source     string
	Topic      string
	TotalCount pgtype.Int4
}

// Marks a (source, topic) pass as complete: bumps the cooldown and clears the cursor.
func (q *Queries) UpsertSyncMetadata(ctx context.Context, arg UpsertSyncMetadataParams) error {
	_, err := q.db.Exec(ctx, upsertSyncMetadata, arg.Source, arg.Topic, arg.TotalCount)
	return err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (source, source_id, username, avatar_url, bio, html_url, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (source, source_id) DO UPDATE SET
  username   = EXCLUDED.username,
  avatar_url = EXCLUDED.avatar_url,
  bio        = EXCLUDED.bio,
  html_url   = EXCLUDED.html_url,
  updated_at = now()
RETURNING id
`

type UpsertUserParams struct {
	Source    string
	SourceID  int64
	Username  string
	AvatarUrl pgtype.Text
	Bio       pgtype.Text
	HtmlUrl   pgtype.Text
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (string, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.Source,
		arg.SourceID,
		arg.Username,
		arg.AvatarUrl,
		arg.Bio,
		arg.HtmlUrl,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
